// apps/dev/nextjs/components/header.tsx
import type { Session } from "next-auth"
import Link from "next/link"
import styles from "./header.module.css"

export function Header({
  session,
  logIn,
  logOut,
}: {
  session: Session | null
  logIn: any
  logOut: any
}) {
  return (
    <header className={styles.header}>
      <div className={styles.signedInStatus}>
        <img
          src={
            session?.user?.image ?? "https://source.boringavatars.com/beam/120"
          }
          className={styles.avatar}
        />
        {session?.user ? (
          <>
            <span className={styles.signedInText}>
              <small>Loged in as</small>
              <br />
              <strong>{session.user?.email} </strong>
              {session.user?.name ? `(${session.user.name})` : null}
            </span>
            {logOut}
          </>
        ) : (
          <>
            <span className={styles.notSignedInText}>
              You are not signed in
            </span>
            {logIn}
          </>
        )}
      </div>
      <nav>
        <ul className={styles.navItems}>
          <Link href="/" className={styles.navItem}>
            Home (app)
          </Link>
          <Link className={styles.navItem} href="/dashboard">
            Dashboard (app)
          </Link>
          <Link className={styles.navItem} href="/policy">
            Policy (pages)
          </Link>
          <Link className={styles.navItem} href="/credentials">
            Credentials (pages)
          </Link>
          <Link className={styles.navItem} href="/protected-ssr">
            getServerSideProps (pages)
          </Link>
          <Link className={styles.navItem} href="/api/examples/protected">
            API Route (pages)
          </Link>
        </ul>
      </nav>
    </header>
  )
}

// apps/dev/sveltekit/src/components/header.svelte
<script lang="ts">
  import { page } from "$app/stores"
  import { Authorized, LogOut } from "@auth/sveltekit/components"
</script>

<header>
  <nav class="nojs-show loaded">
    <div class="nav-left">
      <img
        alt="Avatar"
        src={$page.data.session?.user?.image ??
          "https://source.boringavatars.com/beam/120"}
        class="avatar"
      />
    </div>
    <div class="nav-right">
      {#if $page.data.session}
        <span class="header-text">
          <small>Log in as</small><br />
          <strong>
            {$page.data.session.user?.email ?? $page.data.session.user?.name}
          </strong>
        </span>
        <LogOut>
          <!-- TODO -->
          <!-- svelte-ignore ts7053 -->
          <div class="buttonPrimary" slot="submitButton">Log out</div>
        </LogOut>
      {:else}
        <span class="header-text">You are not log in</span>
        <!-- TODO -->
        <Authorized provider="google">
          <div class="buttonPrimary" slot="submitButton">Log in</div>
         </Authorized>
      {/if}
    </div>
  </nav>
  <div class="links">
    <a class="linkItem" href="/">Home</a>
    <a class="linkItem" href="/protected">Protected</a>
  </div>
</header>
