// packages/core/src/lib/pages/signout.tsx
import type { Theme } from "../../types.js"

export interface SignOutProps {
  url?: URL
  csrfToken?: string
  theme?: Theme
}

export default function SignOutPage(props: SignOutProps) {
  const { url, csrfToken, theme } = props

  return (
    <div className="signout">
      {theme?.brandColor && (
        <style
          dangerouslySetInnerHTML={{
            __html: `
        :root {
          --brand-color: ${theme.brandColor}
        }
      `,
          }}
        />
      )}
      {theme?.buttonText && (
        <style
          dangerouslySetInnerHTML={{
            __html: `
        :root {
          --button-text-color: ${theme.buttonText}
        }
      `,
          }}
        />
      )}
      <div className="card">
        {theme?.logo && <img src={theme.logo} alt="Logo" className="logo" />}
        <h1>logout</h1>
        <p>Are you sure you want to sign out?</p>
        <form action={url?.toString()} method="POST">
          <input type="hidden" name="csrfToken" value={csrfToken} />
          <button id="submitButton" type="submit">
            Log out
          </button>
        </form>
      </div>
    </div>
  )
}

// packages/frameworks-sveltekit/src/lib/components/signout.svelte
<script lang="ts">
  import { enhance } from "$app/forms"
  import type { signout } from "$lib/actions"

  export let className = ""
  export let options: Parameters<typeof signout>[0] = undefined
  export let SignOutPage = "signout"
  
</script>

<form
  method="POST"
  action={`/${SignOutPage}`}
  use:enhance
  class={`logOutButton ${className}`}
  {...$$restProps}
>
  {#if options}
    {#if options?.redirect}
      <input type="hidden" name="redirect" value={options.redirect} />
    {/if}
    {#if options?.redirectTo}
      <input type="hidden" name="redirectTo" value={options.redirectTo} />
    {/if}
  {/if}
  <button type="submit">
    <slot name="submitButton">Sign Out</slot>
  </button>
</form>
